services:
  database:
    image: postgres:latest
    container_name: pg-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-dev_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - 5432:5432
